ui:
  window_title: "Tanuki Leaf"
  window_geometry: "1000x700"
  image_icon: "image/logo.png"

camera:
  device: 0
  frame_width: 640
  frame_height: 480

diffusion:
  t_index_list: [16, 20, 24, 28] # List of time indices for diffusion
  cfg_type: "none"  # Options: none, full, self, initialize
  num_inference_steps: 30  # Number of inference steps
  base_model: "KBlueLeaf/kohaku-v2.1"
  encoder: "madebyollin/taesd"
  use_lora: false
  lora: "lora/satoru.safetensors"

shape:
  default: "rectangle"
  default_position: [100, 100]
  default_size: 100

blur:
  default_slider: 10
  max_value: 100

gesture:
  file: "gesture_library.json"
  similarity_threshold: 0.85
  style_change_gesture: "1"
  use_model: false  # set to true to use ml model
  model_path: "reg_model/hand_gesture_mlp.joblib"
  label_classes: ["1", "2", "naruto", "sakura"]


particles:
  count: 200
  speed_min: 4
  speed_max: 10
  size_min: 3
  size_max: 7
  life_min: 15
  life_max: 35
  gravity_min: 0.05
  gravity_max: 0.2

prompts:
  "satoru": "1guy, (masterpiece),(ultra-detailed),(best quality), blue eyes, (dynamic pose:1.1), short spiky white hair, dressed as a black high-collared sorcerer, surrounded by blue energy and swirling cursed motifs, eyes glow with a playful intensity, holding a blindfold or dark sunglasses, His sorcerer clothes are black with a high collar, The background features a dynamic scene with blue energy alight in vibrant hues of blue and white. Bright rays of energy add an ethereal glow, magical aura that envelops him, casting a gentle luminosity, His presence resonates with a sense of power and mystery, smile, ultra-detailed, 8K,(fantasy:1.2) <lora:add_detail:0.4>, <lora:Silicon-landscape-isolation:1>"
  "naruto": "1guy, (masterpiece),(ultra-detailed),(best quality), orange eyes, (dynamic pose:1.1), short spiky yellow hair, dressed as a orange sporty ninja, surrounded by blue ice balls that roll and spin around him, eyes glow with a tiger-like intensity, holding a grey metal kunai dagger that emanates a cool and strong energy. His ninja clothes are orange with a black zipper and black waistband, The background features a mystical forest with trees alight in vibrant hues of green and white. Bright rays of sunlight add an ethereal glow, magical aura that envelops him, casting a gentle luminosity, His presence resonates with a sense of ancient and elemental power, smile, (fantasy:1.2) <lora:add_detail:0.4>, <lora:Silicon-landscape-isolation:1>"
  "rem": "1girl, (masterpiece),(ultra-detailed),(best quality), blue eyes, (dynamic pose:1.1), short blue hair, dressed as a maid, surrounded by pink petals that float and swirl around her, eyes glow with a soft intensity, holding a morning star that emanates a gentle and strong energy. Her maid clothes are black with white frills and a pink ribbon, The background features a fantasy setting with flowers alight in vibrant hues of pink and white. Bright rays of light add an ethereal glow, magical aura that envelops her, casting a gentle luminosity, Her presence resonates with a sense of determination and grace, smile, (fantasy:1.2) <lora:add_detail:0.4>, <lora:Silicon-landscape-isolation:1>"

negative_prompt: "EasyNegative,badhandv4,(worst quality, low quality:1.4), crowd, (malformed hands:1.4),(poorly drawn hands:1.8),(mutated fingers:1.4),(extra limbs:1.35),(poorly drawn face:1.4),(bad hands:1.4),(malformed anatomy:1.4),(bad anatomy:1.4),(mutated anatomy:1.4), watermark,(mutated legs:1.4),text,twitter username, artist name, bad-hands-5, (text:1.3), hold"
        