ui:
  window_title: "Tanuki Leaf"
  window_geometry: "1000x700"
  image_icon: "image/logo.png"

camera:
  device: 0
  frame_width: 640
  frame_height: 480

diffusion:
  t_index_list: [16, 20, 24, 28] # List of time indices for diffusion
  cfg_type: "none"  # Options: none, full, self, initialize
  num_inference_steps: 30  # Number of inference steps
  base_model: "KBlueLeaf/kohaku-v2.1"
  encoder: "madebyollin/taesd"
  use_lora: true
  lora: "lora/satoru.safetensors"
  controlnet: false


shape:
  default: "rectangle"
  default_position: [100, 100]
  default_size: 100

blur:
  default_slider: 10
  max_value: 100

gesture:
  file: "gesture_library.json"
  similarity_threshold: 0.85
  style_change_gesture: "1"
  use_model: false  # set to true to use ml model
  model_path: "reg_model/hand_gesture_mlp.joblib"
  label_classes: ["1", "2", "naruto", "sakura"]


particles:
  count: 200
  speed_min: 4
  speed_max: 10
  size_min: 3
  size_max: 7
  life_min: 15
  life_max: 35
  gravity_min: 0.05
  gravity_max: 0.2

prompts:
  "satoru": "1guy, (masterpiece:1.3), (ultra-detailed:1.2), (best quality), (official art:1.1), blue eyes, (dynamic pose:1.1), short spiky white hair, (sorcerer outfit:1.3): black high-collared, (blue cursed energy:1.3), (glowing eyes:1.2), (holding blindfold:1.1), (swirling cursed motifs:1.2), (energy aura:1.1), (fantasy background:1.3): vibrant blue/white energy, ethereal glow, (powerful presence:1.1), (playful smirk:1.1), (mysterious aura:1.1), lora:add_detail:0.4, lora:Silicon-landscape-isolation:1"
  "naruto": "1guy, (masterpiece:1.3), (ultra-detailed:1.2), (best quality), (official art:1.1), orange eyes, (dynamic pose:1.1), short spiky yellow hair, (ninja outfit:1.3): orange with black zipper/waistband, (swirling ice balls:1.2), (glowing eyes:1.1), (holding kunai:1.2), (cool energy aura:1.1), (forest background:1.3): mystical green/white trees, sunlight rays, (elemental power:1.1), (determined expression:1.1), (confident smile:1.1), lora:add_detail:0.4, lora:Silicon-landscape-isolation:1"
  "rem": "1girl, (masterpiece:1.3), (ultra-detailed:1.2), (best quality), (official art:1.1), blue eyes, (dynamic pose:1.1), short blue hair, (maid outfit:1.2): black with white frills, pink ribbon, (floating pink petals:1.3), (glowing eyes:1.1), (holding morning star:1.2), (gentle energy aura:1.1), (fantasy background:1.3): vibrant pink/white flowers, ethereal light rays, (magical glow:1.1), (determined expression), (soft smile:1.1), (elegant grace:1.1), lora:add_detail:0.4, lora:Silicon-landscape-isolation:1"
  
negative_prompt: "EasyNegative,badhandv4,(worst quality, low quality:1.4), crowd, (malformed hands:1.4),(poorly drawn hands:1.8),(mutated fingers:1.4),(extra limbs:1.35),(poorly drawn face:1.4),(bad hands:1.4),(malformed anatomy:1.4),(bad anatomy:1.4),(mutated anatomy:1.4), watermark,(mutated legs:1.4),text,twitter username, artist name, bad-hands-5, (text:1.3), hold"

voice_recognition:
  activation_phrase: "activate"
  corrections:
    # rem corrections
    "ram": "rem"
    "run": "rem"
    "rom": "rem"
    "room": "rem"
    "rim": "rem"
    "rome": "rem"
    # satoru corrections
    "satyr": "satoru"
    "setting": "satoru"
    "sitting": "satoru"
    "sato": "satoru"
    "sator": "satoru"
    "settle": "satoru"
    # naruto corrections
    "nuts": "naruto"
    # Add more corrections as needed