ui:
  window_title: "Tanuki Leaf"
  window_geometry: "1000x700"
  image_icon: "image/logo.png"

camera:
  device: 0
  frame_width: 640
  frame_height: 480

diffusion:
  t_index_list: [16, 20, 24, 28] # List of time indices for diffusion
  cfg_type: "none"  # Options: none, full, self, initialize
  num_inference_steps: 30  # Number of inference steps
  base_model: "KBlueLeaf/kohaku-v2.1"
  encoder: "madebyollin/taesd"
  use_lora: true
  lora: "lora/satoru_2.safetensors"
  controlnet: true


shape:
  default: "rectangle"
  default_position: [100, 100]
  default_size: 100

blur:
  default_slider: 10
  max_value: 100

gesture:
  file: "gesture_library.json"
  similarity_threshold: 0.85
  style_change_gesture: "1"
  use_model: false  # set to true to use ml model
  model_path: "reg_model/hand_gesture_mlp.joblib"
  label_classes: ["1", "2", "naruto", "sakura"]


particles:
  count: 200
  speed_min: 4
  speed_max: 10
  size_min: 3
  size_max: 7
  life_min: 15
  life_max: 35
  gravity_min: 0.05
  gravity_max: 0.2

prompts:
  "satoru": "Create an image of Gojo Satoru from Jujutsu Kaisen, featuring his signature white hair, blindfold or dark sunglasses, and his black high-collared outfit. Position him confidently, with a playful smile, against a dynamic background of blue energy and swirling cursed motifs, emphasizing his powerful and enigmatic presence, ultra-detailed, 8K"
  "naruto": "Create an image of Naruto Uzumaki, the beloved ninja from 'Naruto.' Show him with his spiky blond hair, orange jumpsuit, and headband, striking a dynamic pose that reflects his energetic and determined personality. Place him in a vibrant, action-packed setting with swirling chakra energy and iconic ninja symbols, capturing the essence of his adventurous spirit and ninja skills, ultra-detailed, 8K"
  "luffy": "An image of Monkey D. Luffy from 'One Piece.' Depict him with his signature straw hat, red vest, and wide grin, standing confidently with his fists clenched. The background should feature the open sea or a battle scene, emphasizing his adventurous spirit and determination, ultra-detailed, 8K"
  "goku": "Picture of Goku from 'Dragon Ball Z.' Show him in his iconic orange gi, standing in a powerful pose with golden Super Saiyan hair and glowing energy surrounding him. The background should be an intense battle scene with energy blasts and dust clouds, ultra-detailed, 8K"
  "edward": "Drawing of Edward Elric from 'Fullmetal Alchemist.' Show him with his signature red coat, automail arm, and alchemy energy sparking from his hands. The background should have a mysterious transmutation circle glowing with blue light, ultra-detailed, 8K"
  "rem": "Portrayal of Rem from 'Re:Zero.' Show her with her short blue hair, maid outfit, and a soft but determined expression. The background should be a fantasy setting with a hint of magical energy surrounding her, ultra-detailed, 8K"

negative_prompt: "low quality, bad quality, blurry, distorted, malformed hands, unnatural anatomy, overexposed, mutated faces, extra limbs, low resolution, poorly drawn, ugly, deformed, watermark, artifacts, low contrast, washed out colors, pixelated, grainy, noisy, out of focus, poorly lit, overexposed highlights, underexposed shadows, incorrect proportions, awkward poses, unrealistic textures, flat lighting, lack of detail, boring composition, cluttered background"