name: tanuki
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pillow
  - pyyaml
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio
  - pip
  - pip:
    - opencv-python
    - mediapipe
    - msvc-runtime
    - xformers