name: tanuki
channels:
  - nvidia
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pillow
  - pyyaml
  - pip
  - pip:
    - opencv-python
    - mediapipe
    - msvc-runtime
    - xformers
    - --extra-index-url https://download.pytorch.org/whl/cu126
    - torch
    - torchvision
    - torchaudio
    